version: '3'

services:
    web:
        image: nginx:alpine
        container_name: ${PROJECT_NAME}_webserver
        restart: always
        ports:
            - ${WEB_PORT}:80     
        volumes:
            - "./web:/var/www/html"
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - database
            - php

    php:
        image: bitnami/php-fpm
        container_name: ${PROJECT_NAME}_php
        restart: always
        volumes:
            - "./web:/var/www/html"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${PROJECT_NAME}_pma
        restart: always
        ports:
            - ${PMA_PORT}:80
        environment: 
            PMA_HOST: ${PROJECT_NAME}_mysql
            PMA_ARBITRARY: 1
            MYSQL_ROOT_PASSWORD: "root"
        depends_on:
            - database

    database:
        image: mysql:5.7.22
        container_name: ${PROJECT_NAME}_mysql
        restart: always
        ports:
            - ${SQL_PORT}:3306
        volumes:
            - ./data/db/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASS}
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test